{
 "title": "System",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Resource Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(1-rate(node_cpu_seconds_total{mode=\"idle\"}[5m]))",
     "legendFormat": "CPU"
    },
    {
     "expr": "(node_memory_MemTotal_bytes - (node_memory_MemFree_bytes + node_memory_Active_file_bytes + node_memory_Inactive_file_bytes + node_memory_SReclaimable_bytes)) / node_memory_MemTotal_bytes",
     "legendFormat": "RAM"
    },
    {
     "expr": "(sum(node_filesystem_size_bytes{device=~\"/dev/sd.*\"}) - sum(node_filesystem_avail_bytes{device=~\"/dev/sd.*\"})) / sum(node_filesystem_size_bytes{device=~\"/dev/sd.*\"})",
     "legendFormat": "Storage"
    }
   ]
  },
  {
   "title": "Disk Usage (24h)",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(node_disk_read_bytes_total[24h]))",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(increase(node_disk_written_bytes_total[24h]))",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Network Traffic (24h)",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 6, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total[24h]))",
     "legendFormat": "RX"
    },
    {
     "expr": "sum(increase(node_network_transmit_bytes_total[24h]))",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_thermal_zone_temp{type=\"x86_pkg_temp\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Hostname",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_uname_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Threads",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_frequency_max_hertz)",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg by(device) (node_filesystem_size_bytes{device=~\"/dev/sd.*\"}))",
     "legendFormat": "Storage"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Interfaces",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "expr": "node_network_info{device=~\"eth.*|enp.*|wlan.*|wlp.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operating System",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_os_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Kernel Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_uname_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-rate(node_cpu_seconds_total{mode=\"idle\"}[5m])",
     "legendFormat": "CPU #{{cpu}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - (node_memory_MemFree_bytes + node_memory_Active_file_bytes + node_memory_Inactive_file_bytes + node_memory_SReclaimable_bytes)",
     "legendFormat": "RAM"
    },
    {
     "expr": "node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes",
     "legendFormat": "Swap"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device=~\"sd.\"}[5m])",
     "legendFormat": "Read ({{device}})"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{device=~\"sd.\"}[5m])",
     "legendFormat": "Write ({{device}})"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=~\"eth.*|enp.*|wlan.*|wlp.*\"}[5m])",
     "legendFormat": "RX ({{device}})"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device=~\"eth.*|enp.*|wlan.*|wlp.*\"}[5m])",
     "legendFormat": "TX ({{device}})"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_thermal_zone_temp{type=\"x86_pkg_temp\"}",
     "legendFormat": "CPU"
    }
   ]
  }
 ]
}